name: 'Pull-Request Decorator'

description: 'A GitHub Action that takes an input and returns the square of the number'

inputs:
  src_path:
    description: 'Path of source code'
    required: true
    default: "."

  GITHUB_TOKEN:
    description: 'Path of source code'
    required: true
    default: "."

outputs:
  title:
    value: ${{ steps.main.outputs.title }}
  body:
    value: ${{ steps.main.outputs.body }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pipenv'
        cache-dependency-path: ./Pipfile.lock

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv
      shell: bash

    - id: cache-pipenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --dev
      shell: bash
    
    - name: Run main
      id: main
      run: pipenv run python src/main.py
      shell: bash
      env:
        owner: ${{ github.repository_owner }}
        repository: "${{ github.event.repository.name }}"
        pull_request_number: "${{ github.event.pull_request.number }}"
        access_token: "${{ inputs.GITHUB_TOKEN }}"
