name: 'Pull-Request-Typography'

description: 'Pull-Request-Typography'

inputs:
  src_path:
    description: 'Path of source code'
    required: true
    default: "."

  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
    default: "."

runs:
  using: 'composite'
  steps:
    - name: Move to path of action
      run: |
        echo "GITHUB_PATH: $GITHUB_WORKSPACE"
        echo "GITHUB_PATH: $GITHUB_PATH"
        echo "action_path: ${{ github.action_path }}"
        cd ${{ github.action_path }}
        pwd="$(pwd)"
        echo "local_action_path=$pwd" >> $GITHUB_ENV
        echo ${{ env.local_action_path }}
        ls ${{ github.action_path }}
      shell: bash

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pipenv'
        cache-dependency-path: ${{ env.local_action_path }}/Pipfile.lock

    - id: cache-pipenv
      uses: actions/cache@v3
      with:
        path: ${{ env.local_action_path }}/.venv/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install pipenv
      run: |
        cpwd="$(pwd)"
        echo "$cpwd"
        cd ${{ github.action_path }}
        python -m pip install --upgrade pipenv
      shell: bash

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        cd ${{ github.action_path }}
        export PIPENV_VENV_IN_PROJECT=1
        pipenv install --dev
      shell: bash
    
    - name: Run main
      id: main
      run: pipenv run python ${{ env.local_action_path }}/src/main.py
      shell: bash
      env:
        owner: ${{ github.repository_owner }}
        repository: ${{ github.event.repository.name }}
        pull_request_number: ${{ github.event.pull_request.number }}
        access_token: ${{ inputs.GITHUB_TOKEN }}
        src_path: ${{ inputs.src_path }}
