version = 1

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "Pipfile",
  "Pipfile.lock"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 200
  skip_doc_coverage = ["module", "magic", "init"]
  additional_builtins = ["_", "pretty_output"]
