# The pre-commit only runs on the staged contents of files.
repos:
  - repo: local
    hooks:

      - id: flake8
        name: flake8
        entry: pipenv run flake8 --append-config=setup.cfg
        language: system
        types: [file, python]

      - id: pylint
        name: pylint
        entry: pipenv run pylint --rcfile=pylintrc
        language: system
        types: [file, python]

      - id: mypy
        name: mypy
        entry: pipenv run mypy
        language: system
        types: [file, python]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.20.0
    hooks:
      - id: check-jsonschema
        name: "Check GitHub Workflows"
        files: ^\.github/workflows/[^/]+$
        types: [yaml]
        args: ["--schemafile", "https://json.schemastore.org/github-workflow"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: check-yaml
      - id: no-commit-to-branch
        args: ['--pattern', '(?!\((added|changed|deprecated|removed|fixed|security|fix|feat|build|ci|docs|refactor|revert|style|test)\).*)']
