ignore:
  - "hwr_analyzer/services/restful/views/user_notes.py"
  - "hwr_analyzer/services/restful/views/user_pages.py"
  - "hwr_analyzer/services/restful/documents/*.py"
  - "hwr_analyzer/domain/analyzer/**/*.py"
  - "hwr_analyzer/domain/recognizer/services/iink_requester.py"
  - "hwr_analyzer/domain/recognizer/models/raw_content.py"
  - "hwr_analyzer/hwr_analyzer/**/*.py"
  - "hwr_analyzer/hwr_analyzer/*.py"
  - "hwr_analyzer/domain/ndp/services/ndp_requester.py"
  - "hwr_analyzer/manage.py"
  - "hwr_analyzer/serializer.py"
