version: "3.7"
networks:
  hwr-analyzer:

services:
  mongo:
    # 사용할 이미지
    image: mongo
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: mongodb
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "27017:27017"
    # 환경 변수 설정
    environment:
      # MongoDB 계정 및 패스워드 설정 옵션
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # 볼륨 설정
    volumes:
      - ./data/mongodb:/data/db

  redis:
    container_name: redis-dev
    command: --appendonly yes --auto-aof-rewrite-min-size 16mb --stop-writes-on-bgsave-error no
    image: redis:5.0.6-alpine
    networks:
      - hwr-analyzer
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./db/redis/data:/data
