apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  serviceName: celery-beat
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
      - name: celery-beat
        image: icn.ocir.io/cnlkg4dnisfp/hwr-analyzer
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - celery --workdir hwr_analyzer -A hwr_analyzer beat -l info
        envFrom:
          - configMapRef:
              name: base-config
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 300Mi
