apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower
  labels:
    app: celery-flower
  annotations:
    alive: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-flower
  template:
    metadata:
      labels:
        app: celery-flower
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
      - name: celery-flower
        image: mher/flower
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: base-config
