apiVersion: apps/v1
kind: Deployment
metadata:
  name: iink-admin-server
  labels:
    app: iink-admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iink-admin-server
  template:
    metadata:
      labels:
        app: iink-admin-server
    spec:
      containers:
      - name: iink-server
        image: icn.ocir.io/cnlkg4dnisfp/myscript-admin-server:myscript-server-1.5.1-iink
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: temp
            mountPath: /tmp
        envFrom:
          - configMapRef:
              name: base-config
        command:
        - /bin/sh
        - -c
        - /entrypoint.sh
      volumes:
        - name: temp
          emptyDir: {}
