apiVersion: batch/v1
kind: Job
metadata:
  name: kasa-api-db-migration
  labels:
    app.kubernetes.io/name: kasa-api-server
    app.kubernetes.io/part-of: kasa-api
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: service-kasa-api
    spec:
      containers:
      - name: kasa-api-db-migration
        image: kasa-api:prod
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c" ]
        args:
        - python kasa/manage.py showmigrations --database=default;
          python kasa/manage.py migrate --database=default;
          python kasa/manage.py showmigrations --database=left_users;
          python kasa/manage.py migrate --database=left_users;
        envFrom:
        - configMapRef:
            name: kasa-api-config
        - secretRef:
            name: kasa-api-secret
        volumeMounts:
        - mountPath: /etc/ssl/certs/rds-ca-2019-root.pem
          name: ca-certs
          subPath: rds-ca-2019-root.pem
      volumes:
      - name: ca-certs
        configMap:
          name: kasa-api-ca-certs
      restartPolicy: OnFailure
  completions: 1
  parallelism: 1
