apiVersion: v1
kind: Service
metadata:
  labels:
    app: iink-admin-server
  name: iink-admin-server
spec:
  ports:
  - port: 8895
    protocol: TCP
    targetPort: 8895
    nodePort: 32731
  selector:
    app: iink-server
  type: NodePort