apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
  annotations:
    alive: "true"
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 35%
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:latest
          imagePullPolicy: Always
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          name: redis
          ports:
          - containerPort: 6379
            name: redis
          volumeMounts:
          - mountPath: /redis-master-data
            name: data
          - mountPath: /redis-master
            name: config
#          readinessProbe:
#            exec:
#              command: ["sh", "-c", "nc -z localhost 6379"]
#            periodSeconds: 10
#            failureThreshold: 3
#          livenessProbe:
#            exec:
#              command: ["sh", "-c", "nc -z localhost 6379"]
#            initialDelaySeconds: 3
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-config
            items:
            - key: redis-config
              path: redis.conf
