apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  annotations:
    alive: "true"
spec:
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
