name: on-pull-request-action

on:
  pull_request:

jobs:
  integration:
    uses: NeoSmartpen/hwr-api/.github/workflows/django.yml@master
    with:
      ref: ${{ github.ref }}
      base_ref: ${{ github.base_ref }}
  
  add_assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
  
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
