name: Example Action

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  typography:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github.event.pull_request) }}'

      - name: Run main
        id: main
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        #uses: chyccs/pull-request-typography@master
        with:
          language: python
          src_path: "./src/**/*.py"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
